import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

const packagedPath = fileURLToPath(new URL("../packaging/thirdflare-one.service", import.meta.url));
const installScriptPath = fileURLToPath(new URL("../scripts/install-local.sh", import.meta.url));

function parseUnit(text) {
  const sections = {};
  let current = null;
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#") || line.startsWith(";")) continue;
    const header = line.match(/^\[(.+)\]$/);
    if (header) {
      current = header[1];
      sections[current] = sections[current] || {};
      continue;
    }
    const eq = line.indexOf("=");
    if (eq < 1 || !current) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    (sections[current][key] = sections[current][key] || []).push(value);
  }
  return sections;
}

// The user unit is generated by a shell heredoc, so read it back out of the
// installer to catch drift between the two copies.
function extractUserUnit() {
  const script = readFileSync(installScriptPath, "utf8");
  const match = script.match(/cat > "\$SERVICE_FILE" <<SERVICE\n([\s\S]*?)\nSERVICE\n/);
  assert.ok(match, "install-local.sh no longer writes the unit with a <<SERVICE heredoc");
  return match[1];
}

const units = {
  "packaged unit": parseUnit(readFileSync(packagedPath, "utf8")),
  "user unit": parseUnit(extractUserUnit())
};

const requiredService = {
  ProtectSystem: "strict",
  ConfigurationDirectory: "thirdflare",
  ConfigurationDirectoryMode: "0700",
  CacheDirectory: "thirdflare",
  CacheDirectoryMode: "0700",
  RestrictSUIDSGID: "true",
  RestrictNamespaces: "true",
  RestrictRealtime: "true",
  LockPersonality: "true",
  SystemCallArchitectures: "native"
};

// Absent on purpose: NoNewPrivileges and PrivateTmp break the pkexec hop the
// kill switch needs, and MemoryDenyWriteExecute breaks the Node JIT. Adding any
// of them silently disables features that CI cannot exercise, so the unit must
// keep them out until docs/PACKAGING.md says otherwise.
const forbiddenService = ["NoNewPrivileges", "PrivateTmp", "MemoryDenyWriteExecute"];

for (const [label, unit] of Object.entries(units)) {
  test(`${label} applies baseline confinement`, () => {
    for (const [key, value] of Object.entries(requiredService)) {
      assert.deepEqual(unit.Service?.[key], [value], `${key} must be ${value}`);
    }
  });

  test(`${label} keeps pkexec- and JIT-breaking directives out`, () => {
    for (const key of forbiddenService) {
      assert.equal(unit.Service?.[key], undefined, `${key} breaks a shipped feature — see docs/PACKAGING.md`);
    }
  });

  test(`${label} restricts sockets to what the daemon uses`, () => {
    const families = (unit.Service?.RestrictAddressFamilies || [])
      .flatMap((value) => value.split(/\s+/))
      .filter(Boolean);
    assert.deepEqual(families, ["AF_UNIX", "AF_INET", "AF_INET6", "AF_NETLINK"]);
  });

  test(`${label} grants only the writable paths the daemon needs`, () => {
    const paths = (unit.Service?.ReadWritePaths || [])
      .flatMap((value) => value.split(/\s+/))
      .filter(Boolean);
    assert.ok(paths.length > 0, "ProtectSystem=strict needs explicit ReadWritePaths");
    for (const entry of paths) {
      const path = entry.replace(/^-/, "");
      assert.ok(entry.startsWith("-"), `${entry} must be optional (-prefixed) so startup survives a missing path`);
      assert.ok(path !== "/" && path !== "%h" && path !== "/home", `${entry} is too broad`);
    }
  });
}

test("packaged unit is a well-formed user unit", () => {
  const analyze = spawnSync("systemd-analyze", ["--user", "verify", packagedPath], { encoding: "utf8" });
  if (analyze.error) return; // systemd-analyze is absent on macOS and Windows runners.
  const output = `${analyze.stdout || ""}${analyze.stderr || ""}`;
  // A missing pkexec/node on the runner is not a unit problem; unknown or
  // misspelled directives are.
  assert.doesNotMatch(output, /Unknown (?:lvalue|section|key)/i, output);
});
